name: 🐧 Linux Builds
'on':
- push
- pull_request
env:
  GODOT_BASE_BRANCH: 3.5.2-stable
  SCONSFLAGS: '  verbose=yes  '
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Editor w/ Mono (target=release_debug, tools=yes)
          cache-name: linux-editor-mono
          target: release_debug
          tools: true
          sconsflags: module_mono_enabled=yes mono_static=yes mono_glue=no
          bin: ./bin/godot.x11.opt.tools.64.mono
          build-mono: true
          artifact: true
        - name: Editor and sanitizers (target=debug, tools=yes)
          cache-name: linux-editor-sanitizers
          target: debug
          tools: true
          sconsflags: ' '
          test: true
          bin: ./bin/godot.x11.tools.64s
          build-mono: false
          artifact: false
        - name: Template w/ Mono (target=release, tools=no)
          cache-name: linux-template-mono
          target: release
          tools: false
          sconsflags: module_mono_enabled=yes mono_static=yes mono_glue=no debug_symbols=no
          build-mono: false
          artifact: true
        - name: Template sans Mono (target=release, tools=no)
          cache-name: linux-template
          target: release
          tools: false
          sconsflags: debug_symbols=no
          build-mono: false
          artifact: true
        # - name: Template sans Mono (target=release_debug, tools=no)
        #   cache-name: linux-template
        #   target: release_debug
        #   tools: false
        #   sconsflags: debug_symbols=yes
        #   build-mono: false
        #   artifact: true
        - name: Editor sans Mono (target=release_debug, tools=yes)
          cache-name: linux-editor-mono
          target: release_debug
          tools: true
          bin: ./bin/godot.x11.opt.tools.64
          build-mono: false
          artifact: true
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
    - name: Checkout ECMAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/ECMAScript/
    - name: Linux dependencies
      shell: bash
      run: |
        # Azure repositories are not reliable, we need to prevent azure giving us packages.
        sudo rm -f /etc/apt/sources.list.d/*
        sudo cp -f misc/ci/sources.list /etc/apt/sources.list
        sudo apt-get update
        # The actual dependencies
        sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
            libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip
    - name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      with:
        cache-name: ${{ matrix.cache-name }}
      continue-on-error: true
    - name: Setup python and scons
      uses: ./modules/ECMAScript/.github/actions/godot-deps
      with:
        shell: sh
    - name: Compilation
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
        platform: linuxbsd
        target: ${{ matrix.target }}
        tools: ${{ matrix.tools }}
        shell: sh
    - name: Generate Mono glue code
      if: ${{ matrix.build-mono }}
      run: |
        DRI_PRIME=0 xvfb-run ${{ matrix.bin }} --generate-mono-glue modules/mono/glue || true
    - name: Compilation (mono_glue=yes)
      uses: ./modules/ECMAScript/.github/actions/godot-build
      if: ${{ matrix.build-mono }}
      with:
        sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} mono_glue=yes
        platform: linuxbsd
        target: ${{ matrix.target }}
        tools: ${{ matrix.tools }}
        shell: sh
    - name: Download test project
      if: ${{ matrix.test }}
      run: |
        wget https://github.com/godotengine/regression-test-project/archive/3.4.zip
        unzip 3.4.zip
        mv "regression-test-project-3.4" "test_project"
    - name: Open and close editor
      if: ${{ matrix.test }}
      run: |
        DRI_PRIME=0 xvfb-run ${{ matrix.bin }} --audio-driver Dummy -e -q --path test_project 2>&1 | tee sanitizers_log.txt || true
        misc/scripts/check_ci_log.py sanitizers_log.txt
    - name: Run project
      if: ${{ matrix.test }}
      run: |
        DRI_PRIME=0 xvfb-run ${{ matrix.bin }} 30 --video-driver GLES3 --audio-driver Dummy --path test_project 2>&1 | tee sanitizers_log.txt || true
        misc/scripts/check_ci_log.py sanitizers_log.txt
    - name: Check for class reference updates
      if: ${{ matrix.test }}
      run: |
        echo "Running --doctool to see if this changes the public API without updating the documentation."
        echo -e "If a diff is shown, it means that your code/doc changes are incomplete and you should update the class reference with --doctool.\n\n"
        DRI_PRIME=0 xvfb-run ${{ matrix.bin }} --doctool . 2>&1 > /dev/null || true
        git diff --color --exit-code && ! git ls-files --others --exclude-standard | sed -e 's/^/New doc file missing in PR: /' | grep 'xml$'
    - name: Prepare artifact
      if: ${{ matrix.artifact }}
      run: |
        strip bin/godot.*
    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
      if: ${{ matrix.artifact }}
      with:
        name: ${{ matrix.cache-name }}
