name: 🍎 macOS Builds
'on':
- push
- pull_request
env:
  GODOT_BASE_BRANCH: 3.5.2-stable
  SCONSFLAGS: '  verbose=yes   debug_symbols=no'
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true
jobs:
  build-macos:
    runs-on: macos-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Editor (target=release_debug, tools=yes)
          cache-name: macos-editor
          target: release_debug
          tools: true
          bin: ./bin/godot.osx.opt.tools.64
        - name: Template (target=release, tools=no)
          cache-name: macos-template
          target: release
          tools: false
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
    - name: Checkout ECMAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/ECMAScript/
    - name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      with:
        cache-name: ${{ matrix.cache-name }}
      continue-on-error: true
    - name: Setup python and scons
      uses: ./modules/ECMAScript/.github/actions/godot-deps
      with:
        shell: sh
    - name: Compilation
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }}
        platform: osx
        target: ${{ matrix.target }}
        tools: ${{ matrix.tools }}
        shell: sh
    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
      with:
        name: ${{ matrix.cache-name }}
