name: 🍎 macOS Builds
'on':
- push
- pull_request
env:
  GODOT_BASE_BRANCH: 3.6-stable
  SCONSFLAGS: '  verbose=yes   debug_symbols=no'
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true
jobs:
  build-macos:
    runs-on: macos-latest
    name: Editor and Template
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
    - name: Checkout ECMAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/ECMAScript/
    - name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      with:
        cache-name: macos
      continue-on-error: true
    - name: Setup python and scons
      uses: ./modules/ECMAScript/.github/actions/godot-deps
      with:
        shell: sh
    - name: Compilation (release_debug editor)
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: verbose=yes debug_symbols=yes module_mono_enabled=yes mono_static=yes mono_glue=no
        platform: osx
        target: release_debug
        tools: true
        shell: sh
    - name: Generate Mono glue code
      run: |
        ./bin/godot.osx.opt.tools.64.mono --generate-mono-glue modules/mono/glue || true
    - name: Compilation (Editor with mono)
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: verbose=yes debug_symbols=yes module_mono_enabled=yes mono_static=yes mono_glue=yes
        platform: osx
        target: release_debug
        tools: true
        shell: sh
    - name: Compilation (Editor without mono)
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: verbose=yes debug_symbols=yes
        platform: osx
        target: release_debug
        tools: true
        shell: sh
    - name: Compilation (Template with mono)
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: verbose=yes module_mono_enabled=yes mono_static=yes mono_glue=yes debug_symbols=no
        platform: osx
        target: release
        tools: false
        shell: sh
    - name: Compilation (Template without mono)
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: verbose=yes debug_symbols=no
        platform: osx
        target: release
        tools: false
        shell: sh
    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
      with:
        name: macos
