name: 🍎 macOS Builds
'on':
- push
- pull_request
env:
  GODOT_BASE_BRANCH: 3.5.2-stable
  SCONSFLAGS: '  verbose=yes   debug_symbols=no'
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true
jobs:
  build-macos:
    runs-on: macos-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Editor (target=release_debug, tools=yes)
          cache-name: macos-editor
          target: release_debug
          tools: true
          bin: ./bin/godot.osx.opt.tools.64
        - name: Template (target=release, tools=no)
          cache-name: macos-template
          target: release
          tools: false
          debug-opt: ''
        - name: Template (target=release_debug, tools=no)
          cache-name: macos-template
          target: release_debug
          tools: false
          debug-opt: 'debug.'
        - name: Editor w/ Mono (target=release_debug, tools=yes)
          cache-name: macos-editor-mono
          target: release_debug
          tools: true
          sconsflags: module_mono_enabled=yes mono_static=yes mono_glue=no
          bin: ./bin/godot.osx.opt.tools.64.mono
          build-mono: true
          artifact: true
        - name: Editor and sanitizers (target=debug, tools=yes)
          cache-name: osx-editor-sanitizers
          target: debug
          tools: true
          sconsflags: ' '
          test: true
          bin: ./bin/godot.osx.tools.64s
          build-mono: false
          artifact: true
        - name: Template w/ Mono (target=release, tools=no)
          cache-name: osx-template-mono
          target: release
          tools: false
          sconsflags: module_mono_enabled=yes mono_static=yes mono_glue=no debug_symbols=no
          build-mono: false
          artifact: true
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
    - name: Checkout ECMAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/ECMAScript/
    - name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      with:
        cache-name: ${{ matrix.cache-name }}
      continue-on-error: true
    - name: Setup python and scons
      uses: ./modules/ECMAScript/.github/actions/godot-deps
      with:
        shell: sh
    - name: Compilation (x86_64) 
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} arch=x86_64
        platform: osx
        target: ${{ matrix.target }}
        tools: ${{ matrix.tools }}
        shell: sh
    - name: Compilation (arm64) 
      uses: ./modules/ECMAScript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} arch=arm64
        platform: osx
        target: ${{ matrix.target }}
        tools: ${{ matrix.tools }}
        shell: sh
    - name: Universal Binary
      if: ${{ !matrix.tools }}
      shell: bash
      run: lipo -create bin/godot.osx.opt.${{ matrix.debug-opt }}x86_64 bin/godot.osx.opt.${{ matrix.debug-opt }}arm64 -output bin/godot.osx.opt.${{ matrix.debug-opt }}universal
    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
      with:
        name: ${{ matrix.cache-name }}
